<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_RecieptLine_Select</name>
   <tag></tag>
   <elementGuidId>8d5e06c4-06db-41d2-930c-45f0a914270d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8551m001-9-grid-1-tdext851.recd-8-0-widget</value>
   </webElementProperties>
</WebElementEntity>
