<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>08781d07-7a02-42a3-b918-5acfa9e51812</testSuiteGuid>
   <testCaseLink>
      <guid>4023fdb2-8e03-4112-9504-b85d138cf504</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Service/BaseTestCases/Base_Service_CreateHeader</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a6ce029-eb73-4c6b-bdec-15124ccc20d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564c9783-b9ec-4feb-9f66-8d5274b8bd0f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c86e357-6ddb-484b-9547-4936ad9fc981</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Service/BaseTestCases/Base_Service_AddSegment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e775fd69-cb17-4907-8146-35fb1eca7a11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Service/BaseTestCases/Base_Service_Add Others</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b31d1435-fec8-431e-9caf-a47a97019c3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Service/BaseTestCases/Base_Service_HeaderInvoice</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6553563e-1a8b-4ea6-a86c-84e6e1aaeef6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82495eae-d474-4619-9615-1a6ec85a9ab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b339c04f-c616-4f13-b898-a6b17ea9a67c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88f69b42-6508-468f-815e-f1a735f2ebda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>71ae5bfe-4849-4ac0-9d41-b4dd2ec98368</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Service/BaseTestCases/Base_Service_GetInvoice</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
