<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Receipt_SelectLine_SaveNclose</name>
   <tag></tag>
   <elementGuidId>a22f2ee3-b147-4f83-9a2d-a69aa59f1f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8551m001-14-button-std-file.save_and_close</value>
   </webElementProperties>
</WebElementEntity>
