<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_ReceiptLines_SelectLine</name>
   <tag></tag>
   <elementGuidId>3f8c4c6a-1a91-44cb-b904-741c1d5f0e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8551m001-14-grid-1-select-0</value>
   </webElementProperties>
</WebElementEntity>
