<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_LineMMT_SelectFirstRecord</name>
   <tag></tag>
   <elementGuidId>7deab387-9ab5-4e86-9df1-6e677173d1fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8571m000-5-grid-1-select-0</value>
   </webElementProperties>
</WebElementEntity>
