<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Split_Scrollup</name>
   <tag></tag>
   <elementGuidId>1a67f86a-4782-4a3e-b305-5a89da6f0c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xiext8105m000-6-grid-1-scroll-first-image</value>
   </webElementProperties>
</WebElementEntity>
