<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Line_NeworUsed</name>
   <tag></tag>
   <elementGuidId>5d91630e-c2c0-4d6e-ad70-bed201b90eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8151s000-2-used.equipment-18-control-trigger-button</value>
   </webElementProperties>
</WebElementEntity>
