<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_MultiLine_SavenClose</name>
   <tag></tag>
   <elementGuidId>1db8c2f9-24c4-4ab8-9c35-ec820fdf613d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8551m000-1-button-std-file.save_and_close</value>
   </webElementProperties>
</WebElementEntity>
