<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSalesOrder_MMTsavenClose</name>
   <tag></tag>
   <elementGuidId>be61c8e4-1bbb-4969-9665-e8ab36b22b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8571m000-2-button-std-file.save_and_close</value>
   </webElementProperties>
</WebElementEntity>
