<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_RecieptPrint_ProcessCompleted</name>
   <tag></tag>
   <elementGuidId>1193e541-2fcc-4081-8a33-5ceeca07f9a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dlg-tdext8156s000-8-input-button-0</value>
   </webElementProperties>
</WebElementEntity>
