<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_RecieptPrint_Device</name>
   <tag></tag>
   <elementGuidId>93ac7e20-f0db-4831-af85-e3fe64f894fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ttstpsplopen-11-devc-15-lookup-widget</value>
   </webElementProperties>
</WebElementEntity>
