<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Reciept_SaveNClose</name>
   <tag></tag>
   <elementGuidId>5d5d74e4-b6b7-4e5f-94fb-6b63ad5dc56f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8155m000-7-button-std-file.save_and_close</value>
   </webElementProperties>
</WebElementEntity>
