<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Reciept_MeterOK</name>
   <tag></tag>
   <elementGuidId>69296a27-3862-4e73-9de9-24a9c45b1797</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dlg-tdext8156s000-8-input-button-0</value>
   </webElementProperties>
</WebElementEntity>
