<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Reciept_Unit</name>
   <tag></tag>
   <elementGuidId>7008d58b-645c-4f48-9e06-6bb7881d2094</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8156s000-8-grid-1-tdext856.clot-12-0-widget</value>
   </webElementProperties>
</WebElementEntity>
