<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Action_Confirm</name>
   <tag></tag>
   <elementGuidId>33a8c1aa-80e4-4b16-8eb3-60e9eb940ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8156s000-8-menu-std:action-form-conf.receipt</value>
   </webElementProperties>
</WebElementEntity>
