<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Receipt_Action_ReceiptLine</name>
   <tag></tag>
   <elementGuidId>a809ecb8-fa25-487f-9e00-35cded8ce224</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8155m000-7-menu-std:action-form-receipt.lines</value>
   </webElementProperties>
</WebElementEntity>
