<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_MMT_OpenFirstRecord</name>
   <tag></tag>
   <elementGuidId>b99d7a90-5e26-4324-9e0d-c9ad8cae83f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8550m000-6-grid-1-drilldown-0</value>
   </webElementProperties>
</WebElementEntity>
