<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_ReceiptsLines_New</name>
   <tag></tag>
   <elementGuidId>b2c69eb6-f3fa-4777-8086-e3aecdbe9b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8156s000-13-button-std-file.new</value>
   </webElementProperties>
</WebElementEntity>
