<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Action_Reciepts</name>
   <tag></tag>
   <elementGuidId>b9b9b451-101f-47e9-8a62-f4b9a7ff27d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8150s000-7-menu-std:action-form-tdext8555m000</value>
   </webElementProperties>
</WebElementEntity>
