<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSalesOrder_SendForApproval</name>
   <tag></tag>
   <elementGuidId>51bd97f9-26f2-4101-901a-4dc99399d03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8170s000-1-menu-std:action-form-send.for.approval</value>
   </webElementProperties>
</WebElementEntity>
