<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSalesOrder_PO_ok</name>
   <tag></tag>
   <elementGuidId>a6ecb8ad-9409-45ce-b24c-34758a820ba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dlg-tdext8250m999-4-input-button-0</value>
   </webElementProperties>
</WebElementEntity>
