<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSaleOrder_Action_GeneratePO</name>
   <tag></tag>
   <elementGuidId>a83d5db0-6199-4324-be82-72053613fbe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8170s000-1-menu-std:action-form-generate.po</value>
   </webElementProperties>
</WebElementEntity>
