<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_Line_LinkedPO</name>
   <tag></tag>
   <elementGuidId>8ec92e26-861f-43f9-b56d-0c1c3ddefe29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8571m000-5-menu-std:action-form-linked.po</value>
   </webElementProperties>
</WebElementEntity>
