<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Header_Customer</name>
   <tag></tag>
   <elementGuidId>85cad01a-8c57-4903-8b8a-dda2bf51d4e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8150s000-0-tdext850.otbp-1-lookup-widget</value>
   </webElementProperties>
</WebElementEntity>
