<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Print_PrintOption</name>
   <tag></tag>
   <elementGuidId>bc33cb4e-ae96-4e75-9e73-012d3ffc929d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8450m000-3-button-form-exec.cont.process</value>
   </webElementProperties>
</WebElementEntity>
