<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPO_Header_Apporve</name>
   <tag></tag>
   <elementGuidId>4210e2cd-eeca-4f6c-8373-9612e79ec89a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8150s000-0-menu-std:action-form-approve.ammendment</value>
   </webElementProperties>
</WebElementEntity>
