<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCInterface_PaymentGateway</name>
   <tag></tag>
   <elementGuidId>5d10c681-1e71-4cde-a0fc-5a4fae89b3ab</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xiext6102m000-5-pay.gateway-1-lookup-widget</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>pay.gateway-1-lookup-widget</value>
   </webElementProperties>
</WebElementEntity>
