<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_Header_Action_EquipmentDelivery</name>
   <tag></tag>
   <elementGuidId>7abf1e39-e7bc-410c-9a14-362ff1448be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8170s000-1-menu-std:action-form-equip.delivery</value>
   </webElementProperties>
</WebElementEntity>
