<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_Delivery_ActionConfirm</name>
   <tag></tag>
   <elementGuidId>4485f801-d757-44b3-8278-ae9df23149ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8176s000-9-menu-std:action-form-confirm.delivery</value>
   </webElementProperties>
</WebElementEntity>
