<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_DeliveryLine_SelectLine</name>
   <tag></tag>
   <elementGuidId>8768fd4c-fa8d-4bb5-b0ab-1ed68ac77dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8571m001-10-grid-1-tdext871.deli-9-0</value>
   </webElementProperties>
</WebElementEntity>
