<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_EquipDeliveryTab</name>
   <tag></tag>
   <elementGuidId>ec00a9e5-b9a2-4fbe-a90c-4e7f05e6d817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-session-5-tdext8175m000-8</value>
   </webElementProperties>
</WebElementEntity>
