<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_SelectDeliveryLine_SaveNclose</name>
   <tag></tag>
   <elementGuidId>d6ea9952-176f-49a9-9798-008b02cf3aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8571m001-10-button-std-file.save_and_close</value>
   </webElementProperties>
</WebElementEntity>
