<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_Delivery_Action_Line</name>
   <tag></tag>
   <elementGuidId>9b5ea603-eabd-4399-9a26-95d479c5df48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8175m000-8-menu-std:action-form-tdext8176s000</value>
   </webElementProperties>
</WebElementEntity>
