<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Split_3_OrderAmt</name>
   <tag></tag>
   <elementGuidId>6999e397-45a8-46c3-92f8-c29ca8a3fa32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xiext8105m000-6-grid-1-xiext805.oamt.rq-28-2-widget</value>
   </webElementProperties>
</WebElementEntity>
