<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ESO_Line_Unit</name>
   <tag></tag>
   <elementGuidId>af4f4a84-1050-4d2b-8ba1-f45b342292cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8171s000-3-tdext871.clot-15-lookup-widget</value>
   </webElementProperties>
</WebElementEntity>
