<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSalesOrder_ImportNOoption</name>
   <tag></tag>
   <elementGuidId>d81fda36-f150-4c9e-88fd-23cba0c09c91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dlg-tdext8171s000-3-input-button-1</value>
   </webElementProperties>
</WebElementEntity>
