<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSalesOrder_Price</name>
   <tag></tag>
   <elementGuidId>d010cf8e-2a10-4cf0-b32c-a1563caea5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8171s000-3-tdext871.qprc-54-decorator</value>
   </webElementProperties>
</WebElementEntity>
