<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EquipSaleOrder_Save</name>
   <tag></tag>
   <elementGuidId>30f181db-b3ea-4a1a-8efd-fb7ce502b78a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdext8171s000-3-button-std-file.save</value>
   </webElementProperties>
</WebElementEntity>
